### ISSUE TITLE
Add a prebuild hook

### ISSUE THREAD

**Issue by whollacsek** [Scalingo/nodejs-buildpack#5]
I'm looking for a way to customize git just before the build step by executing this kind of command: `git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf git@github.com:`. So that the `npm install` step can point to private github repo.

heroku provides a mechanism to do so https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps, and it seems to be added in the buildpack earlier this year https://github.com/heroku/heroku-buildpack-nodejs/search?utf8=%E2%9C%93&q=heroku-prebuild

**Comment by Soulou** [comment]
Yes it makes sens, we'll backport this feature, without naming the attribute `heroku-*` as your usecase totally makes sense.

**Comment by Soulou** [comment]
You can currently use the scripts:

```
scalingo-prebuild
scalingo-postbuild
```

To add hooks to your build and avoid using the `postinstall` script
