### ISSUE TITLE
We are not installing the latest stable version of node by default

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/nodejs-buildpack#52]
Our buildpack still install v14 which is a Maintenance LTS currently.

The README of our buildpack and our documentation say that we install the latest stable version by default but it's not right:
- https://github.com/Scalingo/nodejs-buildpack#specify-a-node-version
- https://doc.scalingo.com/languages/nodejs/start#specifying-a-nodejs-version

We should install the latest stable version (v17) instead of v14 here: https://github.com/Scalingo/nodejs-buildpack/blob/fc32c0f914553e9aa9e877a660d085cc89457204/lib/binaries.sh#L90

https://nodejs.org/en/about/releases/

Deployment example:
```
-----> Installing binaries
engines.node (package.json):  unspecified
engines.npm (package.json):   unspecified (use default)

Resolving node version 14.x...
Downloading and installing node 14.18.3...
Using default npm version: 6.14.15
```

**Comment by EtienneM** [comment]
This issue should be reported upstream rather than here. We won't fix it. 

Moreover I think the fix should install the latest **LTS** (v16 at the time of writing), not the latest version (v17)

**Comment by 7hibault** [comment]
> This issue should be reported upstream rather than here. We won't fix it.
> 
> Moreover I think the fix should install the latest **LTS** (v16 at the time of writing), not the latest version (v17)

I'm not sure I understand what the decision is, could you please help me understand ?
- Keep the current behaviour, which is installing Maintenance LTS (btw, I see the doc has already been updated :+1: )
- Update the behaviour to install Active LTS, in which case, where could I follow this?

**Comment by EtienneM** [comment]
Hi,

Sorry for my (too) concise message closing this issue.

We want to strictly follow upstream modifications. Hence we won't modify directly this buildpack. We opened an issue on upstream buildpack (https://github.com/heroku/heroku-buildpack-nodejs/issues/972) and are waiting for their answer. We may also open a pull request on the upstream repository if we find the time. But as we don't know whether upstream wants this change, we are not sure it is worth the time to develop  a pull request.

Do you better understand the reason we closed this issue? :)

**Comment by 7hibault** [comment]
Alright, it absolutely makes sense to build upon the upstream buildpack rather than forking and maintaining it. Let's wait and see what the upstream community decides
