### ISSUE TITLE
Update upstream from v211 to v215

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/nodejs-buildpack#76]
Wait v214 release: https://github.com/heroku/heroku-buildpack-nodejs/blob/main/CHANGELOG.md

We can also drop `scalingo-18` support from this buildpack like Heroku does in their changelog

**Comment by analog-nico** [comment]
It would be great if you could upgrade to the v215 soon. It contains x.x.1 versions of v16, v18, and v20 to fix high severity security vulnerabilities as described here: https://nodejs.org/en/blog/vulnerability/june-2023-security-releases

**Comment by analog-nico** [comment]
Worked like a charm. Thank you!
