### ISSUE TITLE
Update upstream from v215 to v217

### ISSUE THREAD

**Issue by Barokai** [Scalingo/nodejs-buildpack#81]
**Is your enhancement request related to a problem? Please describe.**
Similar to https://github.com/Scalingo/nodejs-buildpack/issues/76 please update the upstream heroku-buildpack-nodejs to a newer version (v216 see https://github.com/heroku/heroku-buildpack-nodejs/blob/main/CHANGELOG.md#v216-2023-07-07)

**Describe the solution you'd like**
Enables nodejs version 18.17.0 to be used

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Frzk** [comment]
And up to v217: https://github.com/heroku/heroku-buildpack-nodejs/blob/main/CHANGELOG.md#v217-2023-07-19
